---
include:
  - board: nice_nano_v2
    shield: rossw42_3x4
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: a_dux_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: a_dux_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset